spring:
  profiles:
    active: local


---

spring:
  profiles: local
  datasource:
    url: jdbc:h2:mem:testdb
    data: classpath:data-h2.sql

  jpa:
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop

  h2:
    console:
      enabled: true

